//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanMan.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loan
    {
        public int LoanId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> InterestRateId { get; set; }
        public Nullable<int> RepaymentPeriod { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public Nullable<decimal> Instalment { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> StartPaymentDate { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
    
        public virtual tbl_Client tbl_Client { get; set; }
        public virtual tbl_Interest_Rate tbl_Interest_Rate { get; set; }
    }
}
